[package]
name = "stablecoin-v2-abi"
version = "0.0.0"
authors = [ "you",]
edition = "2024"
publish = false

[dev-dependencies]

[dependencies.stablecoin-v2]
path = ".."

[dependencies.numbat-wasm]
version = "0.20.1"

[dependencies.numbat-wasm-debug]
version = "0.20.1"
